# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hats.proto\",\n\x04\x43hat\x12\x0e\n\x06\x63hatId\x18\x01 \x01(\t\x12\x14\n\x0cparticipants\x18\x02 \x03(\t\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\":\n\rMultipleUsers\x12\x13\n\x0b\x66irstUserId\x18\x01 \x01(\t\x12\x14\n\x0csecondUserId\x18\x02 \x01(\t2H\n\x05\x43hats\x12\x1a\n\x08GetChats\x12\x05.User\x1a\x05.Chat0\x01\x12#\n\nCreateChat\x12\x0e.MultipleUsers\x1a\x05.Chatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHAT']._serialized_start=15
  _globals['_CHAT']._serialized_end=59
  _globals['_USER']._serialized_start=61
  _globals['_USER']._serialized_end=85
  _globals['_MULTIPLEUSERS']._serialized_start=87
  _globals['_MULTIPLEUSERS']._serialized_end=145
  _globals['_CHATS']._serialized_start=147
  _globals['_CHATS']._serialized_end=219
# @@protoc_insertion_point(module_scope)
