# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hats.proto\x1a\x1fgoogle/protobuf/timestamp.proto\",\n\x04\x43hat\x12\x0e\n\x06\x63hatId\x18\x01 \x01(\t\x12\x14\n\x0cparticipants\x18\x02 \x03(\t\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"c\n\x07Message\x12\x0e\n\x06\x63hatId\x18\x01 \x01(\t\x12\x10\n\x08senderId\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12(\n\x04time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\":\n\rMultipleUsers\x12\x13\n\x0b\x66irstUserId\x18\x01 \x01(\t\x12\x14\n\x0csecondUserId\x18\x02 \x01(\t2j\n\x05\x43hats\x12\x1a\n\x08GetChats\x12\x05.User\x1a\x05.Chat0\x01\x12#\n\nCreateChat\x12\x0e.MultipleUsers\x1a\x05.Chat\x12 \n\x0bGetMessages\x12\x05.Chat\x1a\x08.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHAT']._serialized_start=48
  _globals['_CHAT']._serialized_end=92
  _globals['_USER']._serialized_start=94
  _globals['_USER']._serialized_end=118
  _globals['_MESSAGE']._serialized_start=120
  _globals['_MESSAGE']._serialized_end=219
  _globals['_MULTIPLEUSERS']._serialized_start=221
  _globals['_MULTIPLEUSERS']._serialized_end=279
  _globals['_CHATS']._serialized_start=281
  _globals['_CHATS']._serialized_end=387
# @@protoc_insertion_point(module_scope)
